### ISSUE TITLE
makefile empty. unable to create .pdf file

### ISSUE THREAD

**Issue by amrohendawi** [tubav/Thesis#4]
the makefile contains only fixme option which when called returns :

Seems you forgot the checkout the 'lib' using the recursive parameter.
Fixing it for you...
fatal: remote error: upload-pack: not our ref 0658fe9f46d4de220f8634005b75325fe28dd2b2
Fetched in submodule path 'lib', but it did not contain 0658fe9f46d4de220f8634005b75325fe28dd2b2. Direct fetching of that commit failed.
fatal: destination path 'lib' already exists and is not an empty directory.
make: *** [Makefile:6: fixme] Error 128

when cloning the repository I get the following error at the end:

$ sudo git clone --recursive git://github.com/tubav/Thesis.git
Cloning into 'Thesis'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 390 (delta 12), reused 16 (delta 8), pack-reused 360
Receiving objects: 100% (390/390), 1.60 MiB | 2.03 MiB/s, done.
Resolving deltas: 100% (179/179), done.
Updating files: 100% (56/56), done.
Submodule 'lib' (git://github.com/tubav/Core.git) registered for path 'lib'
Cloning into '/mnt/c/Users/test/Desktop/thesis_template/t2/Thesis/lib'...
remote: Enumerating objects: 92, done.
remote: Counting objects: 100% (92/92), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 1353 (delta 49), reused 65 (delta 24), pack-reused 1261
Receiving objects: 100% (1353/1353), 5.17 MiB | 2.04 MiB/s, done.
Resolving deltas: 100% (595/595), done.
fatal: remote error: upload-pack: not our ref 0658fe9f46d4de220f8634005b75325fe28dd2b2
Fetched in submodule path 'lib', but it did not contain 0658fe9f46d4de220f8634005b75325fe28dd2b2. Direct fetching of that commit failed.

please update the repository or at least the documentation

**Comment by AlexanderWillner** [comment]
Thanks - should be fixed now.

**Comment by amrohendawi** [comment]
unfortunately, the problem persists because the folder lib is now called lib@4579a32.
which means whether the makefile needs updating to pull lib@4579a32 instead of lib
or lib@4579a32 should become just lib

**Comment by varungowtham** [comment]
Steps that led to successful creation of rendered PDF file on Ubuntu 20.04. Completely off the shelf.

## Pre-requisites
1. Install libreadline and soft link to a correct shared file. Followed advice from [here](https://askubuntu.com/a/1076284).
```
$ sudo apt install libreadline-dev # install libreadline library
 # make script throws specific error on unavailability of libreadline.so.7
$ sudo ln -s /lib/x86_64-linux-gnu/libreadline.so.8 /lib/x86_64-linux-gnu/libreadline.so.7
```
2. The make script uses the latest texlive library. The one available from ubuntu repository is old.
```
# purge texlive completely
sudo apt purge texlive*
```
3. The template uses features of latest acro package, the one on ubutnu repository is outdated. Download latest release of texlive. Instructions [here on official website](https://www.tug.org/texlive/quickinstall.html). Do not forget to edit .bashrc, to update the path to texlive installation folder.

## Prepare the PDF output
```
$ git clone --recursive git://github.com/tubav/Thesis.git
$ cd Thesis
$ rm -rf lib # this step is somehow needed to force make to download a new version of lib
# skip "make deps-lin", this was already taken care by previous step.
$ make # this downloads lib folder
$ make all # make does not exit with an error
```

**Comment by AlexanderWillner** [comment]
Didn't https://github.com/tubav/Thesis/commit/734fd0682893a1d4b8ba5e86aa7dfa019aea8dee fix the issue with the lib folder and as https://github.com/tubav/Thesis/blob/master/.github/workflows/test.yml works within the GitHub CI system, I wonder why this doesn't work on your machine.

**Comment by varungowtham** [comment]
1. Maybe this is the error, see last three lines:
```
$ git clone --recursive git://github.com/tubav/Thesis.git
Cloning into 'Thesis'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 425 (delta 28), reused 42 (delta 17), pack-reused 360
Receiving objects: 100% (425/425), 1.60 MiB | 1.25 MiB/s, done.
Resolving deltas: 100% (195/195), done.
Submodule 'lib' (git://github.com/tubav/Core.git) registered for path 'lib'
Cloning into '/home/vgo/develop/Thesis/lib'...
remote: Enumerating objects: 105, done.        
remote: Counting objects: 100% (105/105), done.        
remote: Compressing objects: 100% (68/68), done.        
remote: Total 1458 (delta 74), reused 67 (delta 37), pack-reused 1353        
Receiving objects: 100% (1458/1458), 5.18 MiB | 7.12 MiB/s, done.
Resolving deltas: 100% (679/679), done.
fatal: remote error: upload-pack: not our ref 9774adaf0507ea0bfb62815045cbc5f69a740c54
Fetched in submodule path 'lib', but it did not contain 9774adaf0507ea0bfb62815045cbc5f69a740c54. Direct fetching of that commit failed.
```
2. Then executing make by changing into Thesis folder results in an error:
```
$ make clean full
make: *** No rule to make target 'clean'.  Stop.
```

**Comment by AlexanderWillner** [comment]
This is another issue though ;) Fixed in 83046cae8cbee5c4733785f960b8b61a2ce854c4

**Comment by amrohendawi** [comment]
> Steps that led to successful creation of rendered PDF file on Ubuntu 20.04. Completely off the shelf.
> 
> ## Pre-requisites
> 1. Install libreadline and soft link to a correct shared file. Followed advice from [here](https://askubuntu.com/a/1076284).
> 
> ```
> $ sudo apt install libreadline-dev # install libreadline library
>  # make script throws specific error on unavailability of libreadline.so.7
> $ sudo ln -s /lib/x86_64-linux-gnu/libreadline.so.8 /lib/x86_64-linux-gnu/libreadline.so.7
> ```
> 
> 1. The make script uses the latest texlive library. The one available from ubuntu repository is old.
> 
> ```
> # purge texlive completely
> sudo apt purge texlive*
> ```
> 
> 1. The template uses features of latest acro package, the one on ubutnu repository is outdated. Download latest release of texlive. Instructions [here on official website](https://www.tug.org/texlive/quickinstall.html). Do not forget to edit .bashrc, to update the path to texlive installation folder.
> 
> ## Prepare the PDF output
> ```
> $ git clone --recursive git://github.com/tubav/Thesis.git
> $ cd Thesis
> $ rm -rf lib # this step is somehow needed to force make to download a new version of lib
> # skip "make deps-lin", this was already taken care by previous step.
> $ make # this downloads lib folder
> $ make all # make does not exit with an error
> ```

updating texlive to 2020 solved the remaining issue of building the project after following the installation steps.
the issue with the empty lib folder has been solved.

I personally updated tlmgr to 2020 based on this [solution](https://tex.stackexchange.com/a/545502/237528)

**Comment by AlexanderWillner** [comment]
thx for the feedback, I extended the README accordingly
